# Pre-commit hooks to prevent committing large/generated artifacts
# Install: pip install pre-commit && pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
        exclude: |
          (?x)^(
            .*\.pdf$|
            .*\.md$|
            .*\.json$|
            .*\.yaml$|
            .*\.yml$
          )$
      
      - id: check-json
        exclude: ^(results|results_analysis|models|logs)/
      
      - id: trailing-whitespace
        exclude: ^(results|results_analysis|models|logs)/
      
      - id: check-yaml
        exclude: ^(results|results_analysis|models|logs)/
      
      - id: detect-private-key
      
      # Prevent accidental commits of generated outputs
      - id: forbid-files
        args: ['--forbidden-files', 'results_analysis/ results/ models/ logs/']
        exclude: ^(\.gitignore|README\.md)$

