stages:
  download_data:
    cmd: python scripts/download_data.py --manifest data/manifest.csv --out data/raw --extract
    deps:
      - scripts/download_data.py
      - data/manifest.csv
    outs:
      - data/raw
      
  preprocess_deepstarr:
    cmd: python scripts/preprocess_deepstarr.py --raw_dir data/raw --out_dir data/processed
    deps:
      - scripts/preprocess_deepstarr.py
      - data/raw/Sequences_Train.fa
      - data/raw/Sequences_Val.fa
      - data/raw/Sequences_Test.fa
      - data/raw/Sequences_activity_Train.txt
      - data/raw/Sequences_activity_Val.txt
      - data/raw/Sequences_activity_Test.txt
    outs:
      - data/processed/train.txt
      - data/processed/val.txt
      - data/processed/test.txt
      
  train_dream_rnn_ensemble:
    cmd: ./scripts/gpu_wrapper.sh python scripts/train_ensemble.py --model_type dream_rnn --train_data data/processed/train.txt --val_data data/processed/val.txt --output_dir models/dream_rnn_ensemble --n_models 5 --epochs 80 --batch_size 1024 --lr 0.005 --device auto --parallel
    deps:
      - scripts/train_ensemble.py
      - code/models/dream_rnn.py
      - code/models/config.py
      - code/models/__init__.py
      - data/processed/train.txt
      - data/processed/val.txt
    params:
      - train_ensemble.model_type
      - train_ensemble.n_models
      - train_ensemble.epochs
      - train_ensemble.batch_size
      - train_ensemble.lr
    outs:
      - models/dream_rnn_ensemble
      
  predict_ensemble:
    cmd: ./scripts/gpu_wrapper.sh python scripts/predict_ensemble.py --checkpoint_dir models/dream_rnn_ensemble --input_data data/processed/test.txt --output results/test_predictions.csv --device auto
    deps:
      - scripts/predict_ensemble.py
      - code/models/dream_rnn.py
      - code/models/config.py
      - code/models/__init__.py
      - models/dream_rnn_ensemble
      - data/processed/test.txt
    outs:
      - results/test_predictions.csv

  generate_test_val_datasets_deepstarr:
    cmd: ./scripts/gpu_wrapper.sh python scripts/generate_test_val_datasets.py --dataset deepstarr --genomic-test data/processed/test.txt --genomic-val data/processed/val.txt --oracle-dir models/dream_rnn_ensemble --output-dir data/test_val_sets --seed 42
    deps:
      - scripts/generate_test_val_datasets.py
      - code/active_learning/dataset_generators.py
      - configs/test_val_datasets.yaml
      - data/processed/test.txt
      - data/processed/val.txt
      - models/dream_rnn_ensemble
    outs:
      - data/test_val_sets/deepstarr

  test_active_learning:
    cmd: ./scripts/gpu_wrapper.sh python scripts/test_active_learning.py
    deps:
      - scripts/test_active_learning.py
      - code/active_learning
      - models/dream_rnn_ensemble
    outs:
      - results/test_active_learning

  active_learning_random_random_idx1:
    cmd: ./scripts/gpu_wrapper.sh python scripts/run_active_learning.py --config configs/active_learning_random_random.json --run-index 1
    deps:
      - scripts/run_active_learning.py
      - configs/active_learning_random_random.json
      - code/active_learning
      - models/dream_rnn_ensemble
      - data/test_val_sets/deepstarr
    outs:
      - results/deepstarr/5dreamrnn/1deepstarr/100random_proposal/100random_acquisition/100000cand_20000acq/init_prop_random_acq_random_20k/val_genomic/idx1

  active_learning_random_random_idx2:
    cmd: ./scripts/gpu_wrapper.sh python scripts/run_active_learning.py --config configs/active_learning_random_random.json --run-index 2
    deps:
      - scripts/run_active_learning.py
      - configs/active_learning_random_random.json
      - code/active_learning
      - models/dream_rnn_ensemble
      - data/test_val_sets/deepstarr
    outs:
      - results/deepstarr/5dreamrnn/1deepstarr/100random_proposal/100random_acquisition/100000cand_20000acq/init_prop_random_acq_random_20k/val_genomic/idx2

  active_learning_random_random_idx3:
    cmd: ./scripts/gpu_wrapper.sh python scripts/run_active_learning.py --config configs/active_learning_random_random.json --run-index 3
    deps:
      - scripts/run_active_learning.py
      - configs/active_learning_random_random.json
      - code/active_learning
      - models/dream_rnn_ensemble
      - data/test_val_sets/deepstarr
    outs:
      - results/deepstarr/5dreamrnn/1deepstarr/100random_proposal/100random_acquisition/100000cand_20000acq/init_prop_random_acq_random_20k/val_genomic/idx3

  # Genomic initialization experiments (20k acquisition per cycle)
  active_learning_genomic_init_idx1:
    cmd: ./scripts/gpu_wrapper.sh python scripts/run_active_learning.py --config configs/active_learning_genomic_init.json --run-index 1
    deps:
      - scripts/run_active_learning.py
      - configs/active_learning_genomic_init.json
      - code/active_learning
      - models/dream_rnn_ensemble
      - data/test_val_sets/deepstarr
    outs:
      - results/deepstarr/5dreamrnn/1deepstarr/100random_proposal/100random_acquisition/100000cand_20000acq/init_prop_genomic_acq_random_20k/val_genomic/idx1

  active_learning_genomic_init_idx2:
    cmd: ./scripts/gpu_wrapper.sh python scripts/run_active_learning.py --config configs/active_learning_genomic_init.json --run-index 2
    deps:
      - scripts/run_active_learning.py
      - configs/active_learning_genomic_init.json
      - code/active_learning
      - models/dream_rnn_ensemble
      - data/test_val_sets/deepstarr
    outs:
      - results/deepstarr/5dreamrnn/1deepstarr/100random_proposal/100random_acquisition/100000cand_20000acq/init_prop_genomic_acq_random_20k/val_genomic/idx2

  active_learning_genomic_init_idx3:
    cmd: ./scripts/gpu_wrapper.sh python scripts/run_active_learning.py --config configs/active_learning_genomic_init.json --run-index 3
    deps:
      - scripts/run_active_learning.py
      - configs/active_learning_genomic_init.json
      - code/active_learning
      - models/dream_rnn_ensemble
      - data/test_val_sets/deepstarr
    outs:
      - results/deepstarr/5dreamrnn/1deepstarr/100random_proposal/100random_acquisition/100000cand_20000acq/init_prop_genomic_acq_random_20k/val_genomic/idx3

  # Genomic initialization experiments (10k acquisition per cycle)
  # Using YAML batch file for easier reproducibility
  active_learning_genomic_init_10k_batch:
    cmd: ./scripts/gpu_wrapper.sh python scripts/run_experiments.py --config experiments/genomic_init_10k_replicates.yaml --wait
    deps:
      - scripts/run_active_learning.py
      - scripts/run_experiments.py
      - experiments/genomic_init_10k_replicates.yaml
      - configs/active_learning_genomic_init.json
      - code/active_learning
      - models/dream_rnn_ensemble
      - data/test_val_sets/deepstarr
    outs:
      - results/deepstarr/5dreamrnn/1deepstarr/100random_proposal/100random_acquisition/100000cand_10000acq/init_prop_genomic_acq_random_20k/val_genomic/idx4
      - results/deepstarr/5dreamrnn/1deepstarr/100random_proposal/100random_acquisition/100000cand_10000acq/init_prop_genomic_acq_random_20k/val_genomic/idx5
      - results/deepstarr/5dreamrnn/1deepstarr/100random_proposal/100random_acquisition/100000cand_10000acq/init_prop_genomic_acq_random_20k/val_genomic/idx6

  # Or run genomic 20k experiments as a batch
  active_learning_genomic_init_20k_batch:
    cmd: ./scripts/gpu_wrapper.sh python scripts/run_experiments.py --config experiments/genomic_init_replicates.yaml --wait
    deps:
      - scripts/run_active_learning.py
      - scripts/run_experiments.py
      - experiments/genomic_init_replicates.yaml
      - configs/active_learning_genomic_init.json
      - code/active_learning
      - models/dream_rnn_ensemble
      - data/test_val_sets/deepstarr
    outs:
      - results/deepstarr/5dreamrnn/1deepstarr/100random_proposal/100random_acquisition/100000cand_20000acq/init_prop_genomic_acq_random_20k/val_genomic/idx1
      - results/deepstarr/5dreamrnn/1deepstarr/100random_proposal/100random_acquisition/100000cand_20000acq/init_prop_genomic_acq_random_20k/val_genomic/idx2
      - results/deepstarr/5dreamrnn/1deepstarr/100random_proposal/100random_acquisition/100000cand_20000acq/init_prop_genomic_acq_random_20k/val_genomic/idx3

